PhoneResponsive={"785":{
"pageLayer":{"w":785,"h":531,"bgColor":"#ffffff"}
,
"text310099":{"x":142,"y":198,"w":532,"h":333,"txtscale":100,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
},
"480":{
"pageLayer":{"w":480,"h":845,"bgColor":"#ffffff"}
,
"text310099":{"x":87,"y":364,"w":325,"h":481,"txtscale":100,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
}}
